# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scanner:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
         
      - name: Run shiftleft scan
        env:
          CHKP_CLOUDGUARD_ID: ${{ secrets.CHKP_CLOUDGUARD_ID }}
          CHKP_CLOUDGUARD_SECRET: ${{ secrets.CHKP_CLOUDGUARD_SECRET }}
        run: |
          git clone https://github.com/jasonc-cp/demo-app
          chmod +x ./shiftleft
          ./shiftleft code-scan -sevt 4 -s ./demo-app
          
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        env: 
          CHKP_CLOUDGUARD_ID: ${{ secrets.CHKP_CLOUDGUARD_ID }}
          CHKP_CLOUDGUARD_SECRET: ${{ secrets.CHKP_CLOUDGUARD_SECRET }}
        run: |
          git clone https://github.com/jasonc-cp/demo-app
          docker build -t jasonc-cp/myapp ./demo-app
          docker save -o myapp.tar jasonc-cp/myapp
          chmod +x ./shiftleft
          ./shiftleft image-scan -i myapp.tar
          
  verify-infra:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: Check Terra
        env:
          CHKP_CLOUDGUARD_ID: ${{ secrets.CHKP_CLOUDGUARD_ID }}
          CHKP_CLOUDGUARD_SECRET: ${{secrets.CHKP_CLOUDGUARD_SECRET }}
        run: |
          git clone https://github.com/jasonc-cp/demo-app
          chmod +x ./shiftleft
          ./shiftleft iac-assessment -r -64 -p ./demo-app/terraform-template
          
          
          
          
        
        
          
      
          
